version: 2.1

workflows:
  catkin-make:
    jobs:
      - catkin-make-test-laptop
      - catkin-make-test-nano


jobs:
  catkin-make-test-laptop:
    docker:
      - image: diabolokiat/seadrone-project:laptop
    steps:
      - checkout
      - run:
          name: catkin make
          command: 
            source /opt/ros/melodic/setup.bash 
            ./docker/laptop/catkin_make.sh
  
  catkin-make-test-nano:
    docker:
      - image: diabolokiat/seadrone-project:nano
    steps:
      - checkout
      - run:
          name: catkin make
          command: 
            source /opt/ros/melodic/setup.bash 
            ./docker/nano/catkin_make.sh
