version: 2.1

workflows:
  catkin-make:
    jobs:
      - catkin-make-test-laptop

jobs:
  catkin-make-test-laptop:
    docker:
      - image: diabolokiat/seadrone-project:laptop
    steps:
      - checkout
      - run:
          name: catkin make laptop
          command: 
            ./github/git_submodule.sh base
            ./github/git_pull.sh base
            source /opt/ros/melodic/setup.bash 
            ./docker/laptop/catkin_make.sh
            ./environment.sh
